sudo: false
dist: xenial
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.6
- 3.7
#- 3.8
install:
- pip install --upgrade pip wheel
- pip install Cython
- pip install pytest-cov
- pip install coveralls
- make install
script:
- make test
after_success:
- coveralls
- pylint atropos
