sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip wheel
  - pip install Cython
  - pip install .

script:
  - pytest -P tests
